const ReduxActions = {
    SEARCH_FOR_MEMBER: "SEARCH_FOR_MEMBER",
    GET_RECENT_MEMBERS: "GET_RECENT_MEMBERS",
    GET_DISABLED_MEMBERS: "GET_DISABLED_MEMBERS",
    GET_ARCHIVED_MEMBERS: "GET_ARCHIVED_MEMBERS",
    GET_NEARLY_EXPIRED_MEMBERS: "GET_NEARLY_EXPIRED_MEMBERS",
    GET_EXPIRED_MEMBERS: "GET_EXPIRED_MEMBERS",
    RENEW_MEMBERSHIP: "RENEW_MEMBERSHIP",
    UPGRADE_MEMBERSHIP: "UPGRADE_MEMBERSHIP"
};

export default ReduxActions;