const ReduxActions = {
    SEARCH_FOR_MEMBER: "SEARCH_FOR_MEMBER",
    GET_RECENT_MEMBERS: "GET_RECENT_MEMBERS",
    GET_DISABLED_MEMBERS: "GET_DISABLED_MEMBERS",
    GET_ARCHIVED_MEMBERS: "GET_ARCHIVED_MEMBERS",
    GET_NEARLY_EXPIRED_MEMBERS: "GET_NEARLY_EXPIRED_MEMBERS",
    GET_PASSPORT_NEARLY_EXPIRED: "GET_PASSPORT_NEARLY_EXPIRED",
    GET_MEMBER_WITH_BIRTH_DATE: "GET_MEMBER_WITH_BIRTH_DATE",
    GET_EXPIRED_MEMBERS: "GET_EXPIRED_MEMBERS",
    RENEW_MEMBERSHIP: "RENEW_MEMBERSHIP",
    UPGRADE_MEMBERSHIP: "UPGRADE_MEMBERSHIP",
    FETCH_MEMBER_DETAIL: "FETCH_MEMBER_DETAIL",
    GET_MEMBER_ATTACHMENTS: "GET_MEMBER_ATTACHMENTS",
    GET_SERVICES_DETAILS: "GET_SERVICES_DETAILS",
    GET_SERVICES_USAGE: "GET_SERVICES_USAGE",
    GET_WALLET_ACTIONS: "GET_WALLET_ACTIONS"
};

export default ReduxActions;